Draft for nlp tutorial TO BE COMPLETED
control-toolbox/OptimalControl.jl pull request #203
Opened 2024-07-05 09:26 UTC by PierreMartinon

Also some save/load examples added in example_basic tutorial.
Exports for CTDirect functions added.

2024-07-05 10:20 UTC, ocots requested changes

2024-07-05 10:20 UTC, ocots commented on docs/src/tutorial-basic-example.md
> +save_OCP_solution(sol, filename_prefix="my_solution")
Is it useful to call the function `save_OCP_solution` instead of `save`?

2024-07-05 10:20 UTC, ocots commented on docs/src/tutorial-nlp.md
> +docp = directTranscription(ocp)
Shouldn't be `direct_transcription`?

2024-07-05 10:20 UTC, ocots commented on docs/src/tutorial-nlp.md
> +sol = OCPSolutionFromDOCP(docp, dsol)
I think that this should be internal.

2024-07-05 10:20 UTC, ocots commented on docs/src/tutorial-nlp.md
> +plot(sol)
`plot(dsol)`?

2024-07-05 10:20 UTC, ocots commented on docs/src/tutorial-nlp.md
> +nlp = getNLP(docp)
I would remove `get`. It is a function from DOCP to NLP.

`NLP(docp)` or `ADNLPModel(docp)`.

We could have also `ADNLPModel(ocp)`.

2024-07-05 10:20 UTC, ocots commented on docs/src/tutorial-nlp.md
> +setInitialGuess(docp, sol)
`set_initial_guess`.

2024-07-05 10:21 UTC, ocots commented
I have made many remarks that can be discussed.

2024-07-05 10:45 UTC, jbcaillau commented on docs/src/tutorial-nlp.md
> +plot(sol)
@ocots @PierreMartinon doesn't make sense to `plot(dsol)`. Code looks fine to me. Apart from the name, maybe; don't know what the Julian standard is for conversions, BTW. We can always add an alias later if needed.

2024-07-05 10:48 UTC, jbcaillau commented on docs/src/tutorial-nlp.md
> +nlp = getNLP(docp)
@PierreMartinon @ocots I suggest both:
- `get_nlp(ocp)`
 (getter)
- ADNLPModel(ocp)` (converter - see point before for naming, `ADNLPModelFromOCP` is a bit long...)

2024-07-05 10:50 UTC, jbcaillau commented
> I have made many remarks that can be discussed.

@ocots @PierreMartinon thanks for feedback. I vote for BlueStyle (at least standard for most julian things).

2024-07-05 11:15 UTC, PierreMartinon commented on docs/src/tutorial-basic-example.md
> +save_OCP_solution(sol, filename_prefix="my_solution")
It used to be a single function for save / export, with the format passed. The export one cannot really be called just 'export' (?) so it felt a bit weird to call it just 'save', but it could be done. Same for load ?

2024-07-05 11:23 UTC, PierreMartinon commented
Ok, thanks !
- ok for shorter names save / load
- ok also for lower_case_methods (at least the exported ones at first)
- the nlp handling part is not -yet- for common users, so it looks less polished. Working on it though.

I'll update this afternoon

2024-07-05 12:55 UTC, ocots commented
New comments.

2024-07-05 13:15 UTC, PierreMartinon commented on docs/src/tutorial-nlp.md
> +plot(sol)
We could have an extension yes.
Also we could have a simple ```plot(dsol, docp) = plot(ocp_solution_from_docp(docp, dsol))```
even if it's a bit ugly to have to pass docp to plot

2024-07-05 13:19 UTC, jbcaillau commented on docs/src/tutorial-nlp.md
> +plot(sol)
@ocots well, plotting an NLP solution *per se* doesn't make much sense; all in all, I think it's more natural to convert, retrieve the requested information (from `ocp`), and this is exactly what `OCPSolutionFromDOCP` (despite its very long name 😱) does.

NONETHELESS: if any of us wants to add sth else, please do it! Julia spirit! (If there are several good options, don't chose.)

2024-07-05 13:35 UTC, ocots commented
I think you have to add in the `Project.toml` from the doc other packages like `JLD2`.

2024-07-05 14:32 UTC, PierreMartinon commented
New version :-)

2024-07-05 16:18 UTC, PierreMartinon commented on docs/src/tutorial-nlp.md
> +nlp = getNLP(docp)
Ok, which ones ? And don't mix ocp and docp :D

2024-07-05 16:22 UTC, PierreMartinon commented on docs/src/tutorial-nlp.md
> +plot(sol)
Indeed, the NLP solution is just one big vector with everything mixed up inside.
Before we plot we really need to convert it back in terms of ocp functions.
Both methods *ocp_solution_from_docp* and *ocp_solution_from_nlp* are available now, so I think that covers it for now.

2024-07-05 16:25 UTC, PierreMartinon commented on docs/src/tutorial-nlp.md
> +sol = OCPSolutionFromDOCP(docp, dsol)
I reworked this part, tell me what you think.

2024-07-06 19:26 UTC, ocots approved these changes

2024-07-06 19:30 UTC, merged

2024-07-06 19:31 UTC, jbcaillau commented
> New version @ocots @jbcaillau :-)

🙏🏽 @PierreMartinon